// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: proto/planner.proto

package plannerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PathPlanner_Plan_FullMethodName      = "/planner.PathPlanner/Plan"
	PathPlanner_BatchPlan_FullMethodName = "/planner.PathPlanner/BatchPlan"
)

// PathPlannerClient is the client API for PathPlanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PathPlannerClient interface {
	// Plan computes the action for a single robot observation
	Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error)
	// BatchPlan computes actions for multiple robot observations in a single call
	BatchPlan(ctx context.Context, in *BatchPlanRequest, opts ...grpc.CallOption) (*BatchPlanResponse, error)
}

type pathPlannerClient struct {
	cc grpc.ClientConnInterface
}

func NewPathPlannerClient(cc grpc.ClientConnInterface) PathPlannerClient {
	return &pathPlannerClient{cc}
}

func (c *pathPlannerClient) Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error) {
	out := new(PlanResponse)
	err := c.cc.Invoke(ctx, PathPlanner_Plan_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pathPlannerClient) BatchPlan(ctx context.Context, in *BatchPlanRequest, opts ...grpc.CallOption) (*BatchPlanResponse, error) {
	out := new(BatchPlanResponse)
	err := c.cc.Invoke(ctx, PathPlanner_BatchPlan_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PathPlannerServer is the server API for PathPlanner service.
// All implementations must embed UnimplementedPathPlannerServer
// for forward compatibility
type PathPlannerServer interface {
	// Plan computes the action for a single robot observation
	Plan(context.Context, *PlanRequest) (*PlanResponse, error)
	// BatchPlan computes actions for multiple robot observations in a single call
	BatchPlan(context.Context, *BatchPlanRequest) (*BatchPlanResponse, error)
	mustEmbedUnimplementedPathPlannerServer()
}

// UnimplementedPathPlannerServer must be embedded to have forward compatible implementations.
type UnimplementedPathPlannerServer struct {
}

func (UnimplementedPathPlannerServer) Plan(context.Context, *PlanRequest) (*PlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Plan not implemented")
}
func (UnimplementedPathPlannerServer) BatchPlan(context.Context, *BatchPlanRequest) (*BatchPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchPlan not implemented")
}
func (UnimplementedPathPlannerServer) mustEmbedUnimplementedPathPlannerServer() {}

// UnsafePathPlannerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PathPlannerServer will
// result in compilation errors.
type UnsafePathPlannerServer interface {
	mustEmbedUnimplementedPathPlannerServer()
}

func RegisterPathPlannerServer(s grpc.ServiceRegistrar, srv PathPlannerServer) {
	s.RegisterService(&PathPlanner_ServiceDesc, srv)
}

func _PathPlanner_Plan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PathPlannerServer).Plan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PathPlanner_Plan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PathPlannerServer).Plan(ctx, req.(*PlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PathPlanner_BatchPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PathPlannerServer).BatchPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PathPlanner_BatchPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PathPlannerServer).BatchPlan(ctx, req.(*BatchPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PathPlanner_ServiceDesc is the grpc.ServiceDesc for PathPlanner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PathPlanner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "planner.PathPlanner",
	HandlerType: (*PathPlannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Plan",
			Handler:    _PathPlanner_Plan_Handler,
		},
		{
			MethodName: "BatchPlan",
			Handler:    _PathPlanner_BatchPlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/planner.proto",
}
